# Generated by Django 5.0.4 on 2024-04-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='members',
        ),
    ]
