# Generated by Django 5.0.4 on 2024-04-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_alter_member_table'),
    ]

    operations = [
       
    ]
