# Generated by Django 5.0.4 on 2024-04-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_remove_member_profile_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table=None,
        ),
    ]
