# Generated by Django 5.0.4 on 2024-04-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/')),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
    ]
